Add documentation auto-generation zehkira/monophony!169

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -64,6 +64,13 @@ test:
         "$APP_ID" \
         --verbose
 
+    - make --directory=source/ docs
+    - >
+      if ! (git diff --exit-code); then
+        echo "[ERROR] Documentation is outdated - run 'make docs'";
+        false
+      fi
+
 
 build:
   stage: build
